classdef RigidBodyManipulator < Manipulator
  % This class wraps the spatial vector library (v1)
  % provided by Roy Featherstone on his website:
  %   http://users.cecs.anu.edu.au/~roy/spatial/documentation.html

  properties (SetAccess=protected)
    name={};        % names of the objects in the rigid body system
    urdf={};        % names of the urdf files loaded
    body=[];        % array of RigidBody objects
    actuator = [];  % array of RigidBodyActuator objects
    param_db = {};  % cell of structures (one per robot) containing parsed parameter info
    loop=[];        % array of RigidBodyLoop objects
    sensor={};      % cell array of RigidBodySensor objects
    force={};       % cell array of RigidBodyForceElement objects
      % note: need {} for arrays that will have multiple types (e.g.
      % a variety of derived classes), but can get away with [] for arrays
      % with elements that are all exactly the same type
    gravity=[0;0;-9.81];
    dim=3;
    terrain;
    num_contact_pairs;
    contact_options; % struct containing options for contact/collision handling
    contact_constraint_id=[];

    
    % struct containing the output of 'obj.getTerrainContactPoints()'.
    % That output does not change between compilations, and is requested
    % at every simulation dt, so storing it can speed things up.
    cached_terrain_contact_points_struct=[];
    
    quat_norm_constraint_id=[];  % indices of state constraints asserting that the quaternion coordinates have norm=1
    
    % default kinematics caches; temporary way to make it easy to avoid creating
    % and destroying DrakeMexPointers to KinematicsCache every time
    % doKinematics is called
    default_kinematics_cache_ptr_no_gradients = [];
    default_kinematics_cache_ptr_with_gradients = [];
                                            
    frame = [];     % array of RigidBodyFrame objects

    robot_state_frames;
    robot_position_frames;
    robot_velocity_frames;
  end

  properties (Access=public)  % i think these should be private, but probably needed to access them from mex? - Russ
    B = [];
    mex_model_ptr = nullPointer();
    dirty = true;
    collision_filter_groups;  % map of CollisionFilterGroup objects
  end

  methods
    function obj = RigidBodyManipulator(filename,options)
      % Construct a new rigid body manipulator object with a single (empty)
      % RigidBody (called 'world'), and optionally load a first robot from
      % urdf (see documentation for addRobotFromURDF for details on the
      % inputs).

      if (nargin<2), options = struct(); end
      if ~isfield(options,'terrain'), options.terrain = []; end;

      obj = obj@Manipulator(0,0);
      obj.body = RigidBody();
      obj.body.linkname = 'world';
      obj = setTerrain(obj,options.terrain);
      obj.contact_options = obj.parseContactOptions(options);

      obj.collision_filter_groups = PassByValueMap('KeyType','char','ValueType','any');
      obj.collision_filter_groups('no_collision') = CollisionFilterGroup();

      if (nargin>0 && ~isempty(filename))
        [path,name,ext]=fileparts(filename);
        if strcmpi(ext,'.urdf')
          obj = addRobotFromURDF(obj,filename,zeros(3,1),zeros(3,1),options);
        elseif strcmpi(ext,'.sdf') || strcmpi(ext,'.world')
          obj = addRobotFromSDF(obj,filename,zeros(3,1),zeros(3,1),options);
        else
          error('Drake:RigidBodyManipulator:UnsupportedFileExtension','Unrecognized file extension: %s for file %s',ext,name);
        end
      end
    end
  end

  methods (Static)
    function obj = loadobj(obj)
      obj.mex_model_ptr = nullPointer();
      obj = compile(obj);
      % NOTEST
    end
    function contact_options = parseContactOptions(options)
      % contact_options = parseContactOptions(options) returns a struct
      % containing settings for contact/collision detection. If no value
      % is given for a particular setting, a default value is used.
      %
      % @param options - Structure that may have fields specifying
      %                  values for contact options.
      %
      % @retval contact_options - Struct with the following fields:
      %     * ignore_self_collisions          @default false
      %     * replace_cylinders_with_capsules @default true
      %     * use_bullet                      @default checkDependency('bullet')
      %   If a corresponding field exists in `options`, its value will
      %   be used.
      contact_options = struct();
      if isfield(options,'ignore_self_collisions')
        typecheck(options.ignore_self_collisions,'logical');
        contact_options.ignore_self_collisions = options.ignore_self_collisions;
      else
        contact_options.ignore_self_collisions = false;
      end
      if isfield(options,'replace_cylinders_with_capsules')
        typecheck(options.replace_cylinders_with_capsules,'logical');
        contact_options.replace_cylinders_with_capsules = ...
          options.replace_cylinders_with_capsules;
      else
        contact_options.replace_cylinders_with_capsules = true;
      end
      if isfield(options,'use_bullet')
        typecheck(options.use_bullet,'logical');
        if options.use_bullet
          checkDependency('bullet')
        end
        contact_options.use_bullet = options.use_bullet;
      else
        contact_options.use_bullet = checkDependency('bullet');
      end
      % NOTEST
    end
  end

  methods
    function [Vq, dVq] = qdotToV(obj, q)
      compute_gradient = nargout > 1;

      bodies = obj.body;
      nb = length(bodies);
      nv = obj.num_velocities;
      nq = obj.num_positions;
      Vq = zeros(nv, nq) * q(1); % to make TaylorVar work better

      if compute_gradient
        dVq = zeros(numel(Vq), nq) * q(1);
      end
      for i = 2 : nb
        bodyI = bodies(i);
        q_body = q(bodyI.position_num);
        if compute_gradient
          [VqJoint, dVqJoint] = jointQdot2v(bodyI, q_body);
          dVq = setSubMatrixGradient(dVq, dVqJoint, bodyI.velocity_num, bodyI.position_num, size(Vq), bodyI.position_num);
        else
          VqJoint = jointQdot2v(bodyI, q_body);
        end
        Vq(bodyI.velocity_num, bodyI.position_num) = VqJoint;
      end
    end

    function [VqInv, dVqInv] = vToqdot(obj, q)
      compute_gradient = nargout > 1;

      bodies = obj.body;
      nb = length(bodies);
      nv = obj.num_velocities;
      nq = obj.num_positions;
      VqInv = zeros(nq, nv) * q(1); % to make TaylorVar work better

      if compute_gradient
        dVqInv = zeros(numel(VqInv), nq) * q(1);
      end
      for i = 2 : nb
        bodyI = bodies(i);
        q_body = q(bodyI.position_num);
        if compute_gradient
          [VqInvJoint, dVqInvJoint] = jointV2qdot(bodyI, q_body);
          dVqInv = setSubMatrixGradient(dVqInv, dVqInvJoint, bodyI.position_num, bodyI.velocity_num, size(VqInv), bodyI.position_num);
        else
          VqInvJoint = jointV2qdot(bodyI, q_body);
        end
        VqInv(bodyI.position_num, bodyI.velocity_num) = VqInvJoint;
      end
    end

    function y = output(obj,t,x,u)
      % The outputs of this dynamical system are concatenated from each of
      % the sensors.  If no sensor has been added to the system, then the
      % output defaults to the full robot state.

      checkDirty(obj);

      if isempty(obj.sensor)
        y = x;
      else
        if ~isDirectFeedthrough(obj)
          u=[];
        end
        y = [];
        for i=1:length(obj.sensor)
          y = [y; obj.sensor{i}.output(obj,t,x,u)];
        end
      end
    end

    function obj = setTerrain(obj,terrain)
      % Set the ground height profile which the contact points on the robot
      % may not penetrate.
      %
      % @param terrain a RigidBodyTerrain object

      if ~isempty(terrain)
        typecheck(terrain,'RigidBodyTerrain');
      end
      obj = removeTerrainGeometry(obj);
      obj.terrain = terrain;
      obj = addTerrainGeometry(obj);
    end

    function obj = addTerrainGeometries(varargin)
      errorDeprecatedFunction('addTerrainGeometry')
    end

    function obj = addTerrainGeometry(obj)
      if ~isempty(obj.terrain)
        geom = obj.terrain.getCollisionGeometry();
        if ~isempty(geom)
          if ~iscell(geom), geom={geom}; end
          for i=1:numel(geom)
            if ~any(cellfun(@(geometry) isequal(geom{i},geometry),obj.body(1).collision_geometry))
              obj = obj.addCollisionGeometryToBody(1,geom{i},'terrain');
              obj.dirty = true;
            end
          end
        end
        geom = obj.terrain.getVisualGeometry();
        if ~isempty(geom)
          if ~iscell(geom), geom={geom}; end
          for i=1:numel(geom)
            if ~any(cellfun(@(geometry) isequal(geom{i},geometry),obj.body(1).visual_geometry))
              obj.body(1).visual_geometry{end+1} = geom{i};
              obj.dirty = true;
            end
          end
        end
      end
    end

    function obj = removeTerrainGeometries(varargin)
      errorDeprecatedFunction('removeTerrainGeometry');
    end

    function obj = removeTerrainGeometry(obj)
      if ~isempty(obj.terrain)
        geom = obj.terrain.getCollisionGeometry();
        geom_contact_idx = cellfun(@(geometry) isequal(geom,geometry),obj.body(1).collision_geometry);
        obj.body(1).collision_geometry(geom_contact_idx) = [];

        geom = obj.terrain.getVisualGeometry();
        geom_visual_idx = cellfun(@(geometry) isequal(geom,geometry),obj.body(1).visual_geometry);
        obj.body(1).visual_geometry(geom_visual_idx) = [];

        obj.dirty = true;
      end
    end

    function [z,normal] = getTerrainHeight(obj,contact_pos)
      % Access method for querying the terrain height from the
      % RigidBodyTerrain object assigned to this manipulator
      %
      % @param contact_pos a 2xN or 3xN list of positions in the world
      % frame below which to compute the height of the terrain.
      %
      % @retval z a 1xN list of terrain heights in world coordinates
      % @retval normal a 3xN list of surface normals in world cooridinates

      [z,normal] = getHeight(obj.terrain,contact_pos(1:2,:));
    end

    function B = getB(obj,q,qd)
      % Note:  getB(obj) is ok iff there are no direct feedthrough force
      % elements.
      checkDirty(obj);

      B = obj.B;
      if length(obj.force)>0
        for i=1:length(obj.force)
          if (obj.force{i}.direct_feedthrough_flag)
            [~,B_force] = computeSpatialForce(obj.force{i},obj,q,qd);
            B = B+B_force;
          end
        end
      end

    end
    function n = getNumBodies(obj)
      % @ingroup Kinematic Tree
      n = length(obj.body);
    end

    function str = getLinkName(obj,body_ind)
      % str = getLinkName(obj,body_ind) returns a string containing the
      % link name the specified body if body_ind is a scalar. If body
      % ind is a vector, it returns a cell array containing the names of
      % the bodies specified by the elements of body_ind.
      %
      % @param obj - RigidBodyManipulator object
      % @param body_ind - Body index or vector of body indices
      %
      % @retval str - String (cell array of strings) containing the
      % requested linkname(s)
      %
      % @ingroup Kinematic Tree

      if numel(body_ind) > 1
        str = {obj.body(body_ind).linkname};
      else
        str = obj.body(body_ind).linkname;
      end
    end

    function obj = setGravity(obj,grav)
      sizecheck(grav,size(obj.gravity));
      obj.gravity = grav;
      obj.dirty = true;
    end
    
    function q0 = getRandomConfiguration(obj)
      q0 = zeros(getNumPositions(obj),1);
      for i=1:getNumBodies(obj)
        if any(obj.body(i).position_num>0)
          q0(obj.body(i).position_num) = getRandomConfiguration(obj.body(i));
        end
      end
    end
    
    function x0 = getInitialState(obj)
      if ~isempty(obj.initial_state)
        x0 = obj.initial_state;
        return;
      end
      
      x0 = [ getRandomConfiguration(obj); .01*randn(getNumVelocities(obj),1)];
      if ~isempty(obj.state_constraints)
        attempts=0;
        success=false;
        while (~success)
          attempts=attempts+1;
          try
            [x0,success] = resolveConstraints(obj,x0);
          catch ex
            if strcmp(ex.identifier,'Drake:DrakeSystem:FailedToResolveConstraints');
              success=false;
            else
              rethrow(ex);
            end
          end
          if (~success)
            x0 = randn(obj.num_xd+obj.num_xc,1);
            if (attempts>=10)
              error('Drake:DrakeSystem:FailedToResolveConstraints','Failed to resolve state constraints on initial conditions after 10 tries');
            end
          end
        end
      end
      x0 = double(x0);      
    end

    function obj = setJointLimits(obj,jl_min,jl_max)
      obj = setJointLimits@Manipulator(obj,jl_min,jl_max);
      obj.dirty = true;
      for i = 1:getNumBodies(obj)
        pos_num = obj.body(i).position_num;
        if(any(pos_num~= 0)) % not the world body
          obj.body(i).joint_limit_min = jl_min(pos_num)';
          obj.body(i).joint_limit_max = jl_max(pos_num)';
        end
      end
    end

    function g = getGravity(obj,grav)
      g = obj.gravity;
    end

    function [f_friction, df_frictiondv] = computeFrictionForce(model,v)
      % Note: gradient is with respect to v, not q!
      compute_gradient = nargout > 1;

      nv = model.getNumVelocities();
      damping = zeros(nv, 1);
      coulomb_friction = zeros(nv, 1);
      static_friction = zeros(nv, 1);
      coulomb_window = zeros(nv, 1);

      for i = 2 : model.getNumBodies()
        b = model.body(i);
        damping(b.velocity_num) = b.damping;
        coulomb_friction(b.velocity_num) = b.coulomb_friction;
        static_friction(b.velocity_num) = b.static_friction;
        coulomb_window(b.velocity_num) = b.coulomb_window;
      end

      f_friction = damping .* v;
      if compute_gradient
        df_frictiondv = diag(damping);
      end

      if any(coulomb_friction)
        f_friction = f_friction + min(1,max(-1,v./coulomb_window)).*coulomb_friction;
        if compute_gradient
          ind = find(abs(v)<coulomb_window');
          dind = sign(v(ind))./coulomb_window(ind)' .* coulomb_friction(ind)';
          fc_drv = zeros(model.getNumVelocities(),1);
          fc_drv(ind) = dind;
          df_frictiondv = df_frictiondv + diag(fc_drv);
        end
      end
    end

    function ptr = getMexModelPtr(obj)
      % Please do note use this.
      % This access should not be allowed (the method should be private or not exist).
      % But it is currently used by QPControlBlock to pass to QPControllermex in drc/software/control
      ptr = obj.mex_model_ptr;
    end

    function [f,dfdq,dfdforce] = cartesianForceToSpatialForce(obj,kinsol,body_ind,point,force)
      % @param body_ind is an index of the body
      % @param point is a point on the rigid body (in body coords)
      % @param force is a cartesion force (in world coords)

      % convert force to body coordinates
      if (nargout>1)
        [ftmp,ftmpP,ftmpJ]=bodyKin(obj,kinsol,body_ind,[force,zeros(3,1)]);
      else
        ftmp=bodyKin(obj,kinsol,body_ind,[force,zeros(3,1)]);
      end

      % try to do it the Xtree way
      force = ftmp(:,1)-ftmp(:,2);
      f = [ cross(point,force,1); force ];  % spatial force in body coordinates

      if (nargout>1)
        dforcedq = ftmpJ(1:3,:)-ftmpJ(4:6,:);
        dforcedforce = ftmpP(1:3,1:size(force,1))-ftmpP(4:6,1:size(force,1));
        dfdq = [ cross(repmat(point,1,size(dforcedq,2)),dforcedq); dforcedq ];
        dfdforce = [ cross(repmat(point,1,size(dforcedforce,2)),dforcedforce); dforcedforce];
      end
    end

    function [model,id]=addLink(model,b)
      % @ingroup Kinematic Tree
      typecheck(b,'RigidBody');
      sizecheck(b,1);
      model.body = [model.body,b];
      id = length(model.body);
      model.dirty = true;
    end

    function model=addJoint(model,name,type,parent_ind,child_ind,xyz,rpy,axis,damping,coulomb_friction,static_friction,coulomb_window,limits)
      % @ingroup Kinematic Tree
      typecheck(parent_ind,'double');
      typecheck(child_ind,'double');
      if (nargin<6) xyz=zeros(3,1); end
      if (nargin<7) rpy=zeros(3,1); end
      if (nargin<8) axis=[1;0;0]; end
   <x>25.216793</x>
            <y>20.86734</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>20.66743</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>20.467521</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>20.267611</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>20.067702</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>19.867792</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>19.667883</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>19.467973</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>19.268064</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>19.068155</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>18.868245</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>18.668336</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>18.468426</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>18.268517</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>18.068607</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>17.868698</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>17.668788</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>17.468879</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>17.268969</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>17.06906</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>16.86915</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>16.669241</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>16.469331</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>16.269422</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>16.069512</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>15.869603</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>15.669693</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>15.469784</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>15.269874</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>15.069965</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>14.870055</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>14.670146</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>14.470236</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>14.270327</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>14.070417</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>13.870508</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>13.670598</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>13.470689</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>13.270779</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>13.07087</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>12.87096</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>12.671051</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>12.471141</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>12.271232</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>12.071322</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>11.871413</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>11.671504</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>11.471594</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>11.271684</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>11.071775</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>10.871865</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>10.671956</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>10.472046</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>10.272137</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>10.072227</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>9.872318</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>9.672408</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>9.472499</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>9.272589</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>9.07268</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>8.87277</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>8.672861</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>8.472951</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>8.273042</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>8.073132</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>7.873223</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>7.673313</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>7.473404</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>7.273494</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>7.073585</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>6.873675</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>6.673766</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>6.473857</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>6.273946</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>6.074037</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>24.919171</x>
            <y>5.800879</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.008734</x>
            <y>5.749695</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.216793</x>
            <y>5.874128</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.217013</x>
            <y>5.673933</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.186539</x>
            <y>5.653759</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.121753</x>
            <y>5.687843</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.796708</x>
            <y>28.043966</y>
            <z>7.8859</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.278935</x>
            <y>28.131487</y>
            <z>9.986708</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.317411</x>
            <y>27.997061</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>27.741108</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.417147</x>
            <y>27.928894</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>27.553521</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>27.365935</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>27.178347</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>26.99076</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>26.803174</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>26.615587</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>26.427999</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>26.240413</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>26.052826</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>25.677652</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>25.865239</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.414174</x>
            <y>25.491776</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.36387</x>
            <y>25.401609</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.315084</x>
            <y>25.253795</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.364717</x>
            <y>24.950505</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.315376</x>
            <y>25.098136</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>24.682946</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.412062</x>
            <y>24.877067</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>24.485128</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>24.287311</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>24.089493</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>23.891675</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>23.693858</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>23.49604</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>23.298223</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>23.100405</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>22.902587</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>22.70477</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>22.506952</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>22.309134</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>22.111317</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>21.913499</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>21.715682</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>21.517864</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>21.320047</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>21.122229</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>20.924411</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>20.726593</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>20.528776</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>20.330958</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>20.133141</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>19.935323</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>19.737506</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>19.539688</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>19.34187</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>19.144053</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>18.946235</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>18.748417</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>18.5506</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>18.352782</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>18.154965</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>17.957147</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>17.759329</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>17.561512</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>17.363694</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>17.165877</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>16.968059</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>16.770241</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>16.572424</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>16.374606</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>16.176788</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>15.978971</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>15.781153</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>15.583336</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>15.385518</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>15.1877</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>14.989883</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>14.792065</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>14.594248</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>14.39643</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>14.198612</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>14.000795</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>13.802977</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>13.60516</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>13.407342</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>13.209524</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>13.011707</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>12.813889</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>12.616071</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>12.418254</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>12.220436</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>12.022619</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>11.824801</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>11.626984</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>11.429166</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>11.231348</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>11.033531</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>10.835713</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>10.637895</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>10.440078</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>10.24226</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>10.044443</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>9.846625</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>9.648807</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>9.45099</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>9.253172</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>9.055354</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.412062</x>
            <y>8.861233</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.315376</x>
            <y>8.640164</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.364717</x>
            <y>8.787795</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.36387</x>
            <y>8.336691</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.315084</x>
            <y>8.484506</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.414196</x>
            <y>8.246518</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>8.060755</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>7.873159</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>7.497968</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>7.685563</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>7.310372</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>7.122776</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>6.93518</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>6.747584</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>6.559989</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>6.372393</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>6.184797</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.416993</x>
            <y>5.997201</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.417147</x>
            <y>5.809406</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.277808</x>
            <y>5.607217</y>
            <z>9.986996</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.317411</x>
            <y>5.74124</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.289674</x>
            <y>5.601343</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>27.297281</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.143304</x>
            <y>27.25455</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.164392</x>
            <y>27.37409</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.151996</x>
            <y>27.301942</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.018084</x>
            <y>27.489149</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.180451</x>
            <y>27.475273</y>
            <z>9.986996</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.182372</x>
            <y>27.488374</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>27.106049</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.120959</x>
            <y>27.139976</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.097287</x>
            <y>27.030388</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.11611</x>
            <y>27.116489</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>26.914818</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.072324</x>
            <y>26.925775</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.074012</x>
            <y>26.932348</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.019891</x>
            <y>26.730995</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.025334</x>
            <y>26.749835</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017613</x>
            <y>26.723207</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>26.902288</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>26.717687</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.965378</x>
            <y>26.555218</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.969979</x>
            <y>26.569234</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>27.086888</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>27.271489</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>27.456089</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.926149</x>
            <y>27.559789</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.033988</x>
            <y>27.589829</y>
            <z>9.986937</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817906</x>
            <y>27.641356</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.885707</x>
            <y>27.702306</y>
            <z>9.986937</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>26.533086</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.910465</x>
            <y>26.397878</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>26.348486</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.856448</x>
            <y>26.257549</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.907802</x>
            <y>26.390869</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817456</x>
            <y>26.162841</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.839146</x>
            <y>26.214899</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>26.189551</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>25.989829</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.803754</x>
            <y>26.131175</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>26.389273</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>26.588995</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>26.788716</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>26.988438</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>27.18816</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>27.387882</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>27.587603</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.683758</x>
            <y>27.740097</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.735893</x>
            <y>27.812732</y>
            <z>9.986937</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617602</x>
            <y>27.787857</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.757159</x>
            <y>26.029348</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.763127</x>
            <y>26.041957</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.707849</x>
            <y>25.933621</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.618535</x>
            <y>25.789231</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.674356</x>
            <y>25.875194</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.59512</x>
            <y>25.755164</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.527688</x>
            <y>27.851795</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.584573</x>
            <y>27.921087</y>
            <z>9.986937</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.437221</x>
            <y>27.915015</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.431777</x>
            <y>28.027351</y>
            <z>9.986937</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.533455</x>
            <y>25.669295</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.569018</x>
            <y>25.718465</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.472646</x>
            <y>25.582733</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.459938</x>
            <y>25.564097</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.36387</x>
            <y>25.401609</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.315084</x>
            <y>25.253795</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.315376</x>
            <y>25.098136</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.364717</x>
            <y>24.950505</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.458077</x>
            <y>24.825952</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617313</x>
            <y>24.66926</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.601176</x>
            <y>24.685431</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>24.469121</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>24.269122</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>24.069122</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>23.869123</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>23.669123</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>23.469124</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>23.269125</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>23.069126</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>22.869127</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>22.669127</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>22.469128</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>22.269129</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>22.06913</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>21.86913</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>21.669131</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>21.469131</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>21.269132</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>21.069133</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>20.869134</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>20.669135</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>20.469135</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>20.269136</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>20.069137</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>19.869137</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>19.669138</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>19.469139</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>19.269139</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>19.06914</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>18.869141</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>18.669142</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>18.469142</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>18.269143</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>18.069144</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>17.869145</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>17.669145</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>17.469146</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>17.269147</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>17.069147</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>16.869148</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>16.669149</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>16.46915</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>16.26915</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>16.069151</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>15.869152</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>15.669152</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>15.469153</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>15.269154</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>15.069155</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>14.869155</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>14.669156</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>14.469157</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>14.269158</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>14.069158</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>13.869159</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>13.66916</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>13.469161</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>13.269161</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>30.738737</x>
            <y>13.295704</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>13.069162</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>12.869163</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>12.669163</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>12.469164</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>12.269165</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>12.069165</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>11.869166</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>11.669167</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>11.469168</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>11.269169</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>11.069169</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>10.86917</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>10.66917</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>10.469171</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>10.269172</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>10.069173</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>9.869173</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>9.669174</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>9.469175</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>9.269176</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617336</x>
            <y>9.069062</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.458077</x>
            <y>8.912348</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.601419</x>
            <y>9.053112</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.458077</x>
            <y>8.912348</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.364717</x>
            <y>8.787795</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.315376</x>
            <y>8.640164</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.315084</x>
            <y>8.484506</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.36387</x>
            <y>8.336691</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.473859</x>
            <y>8.153786</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.460138</x>
            <y>8.173905</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.597371</x>
            <y>7.979934</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.535213</x>
            <y>8.066559</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>7.74862</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.618401</x>
            <y>7.949249</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>7.548881</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>7.349143</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>7.149405</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>6.949666</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>6.749928</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>6.55019</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>6.350451</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617193</x>
            <y>6.150713</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.617602</x>
            <y>5.950443</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.432015</x>
            <y>5.711113</y>
            <z>9.986937</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.527688</x>
            <y>5.886506</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>20.411993</x>
            <y>5.849753</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.437221</x>
            <y>5.823285</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.584809</x>
            <y>5.81738</y>
            <z>9.986937</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.458077</x>
            <y>24.825952</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.553826</x>
            <y>24.732494</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.741895</x>
            <y>24.542134</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.648437</x>
            <y>24.637883</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>24.304282</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.807295</x>
            <y>24.485393</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>24.106012</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>23.907742</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>23.709472</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>23.511201</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>23.312931</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>23.114661</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>22.916391</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>22.718121</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>22.51985</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>22.32158</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>22.12331</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>21.92504</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>21.72677</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>21.528499</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>21.330229</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>21.131959</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>20.933689</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>20.735419</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>20.537148</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>20.338878</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>20.140608</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>19.942338</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>19.744068</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>19.545798</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>19.347527</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>19.149257</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>18.950987</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>18.752717</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>18.554447</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>18.356176</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>18.157906</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>17.959636</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>17.761366</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>17.563096</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>17.364826</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>17.166555</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>16.968285</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>16.770015</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>16.571745</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>16.373475</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>16.175204</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>15.976934</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>15.778664</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>15.580394</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>15.382124</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>15.183854</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>14.985583</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>14.787313</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>14.589043</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>14.390773</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>14.192503</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>13.994232</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>13.795962</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>13.597692</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>13.399422</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>13.201152</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>13.002881</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>12.804611</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>12.606341</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>12.408071</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>12.209801</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>12.011531</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>11.813261</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>11.614991</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>11.41672</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>11.21845</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>11.02018</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>10.82191</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>10.62364</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>10.425369</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>10.227099</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>10.028829</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>9.830559</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>9.632289</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.817393</x>
            <y>9.434018</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.741895</x>
            <y>9.196166</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>20.612193</x>
            <y>9.169838</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.807295</x>
            <y>9.252907</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.648437</x>
            <y>9.100417</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.741895</x>
            <y>9.196166</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.553826</x>
            <y>9.005806</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.741895</x>
            <y>24.542134</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.905707</x>
            <y>24.430377</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>25.866448</x>
            <y>24.448774</y>
            <z>9.8</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>24.201814</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.014079</x>
            <y>24.399433</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>24.003634</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>23.805454</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>23.607274</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>23.409094</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>23.210914</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>23.012734</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>22.814554</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>22.616374</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>22.418194</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>22.220013</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>22.021833</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>21.823653</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>21.625473</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>21.427293</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>21.229113</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>21.030933</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>20.832752</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>20.634572</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>20.436392</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>20.238212</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>20.040032</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>19.841852</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>19.643672</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>19.445492</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>19.247312</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>19.049131</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>18.850951</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>18.652771</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>18.454591</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>18.256411</y>
            <z>10</z>
          </coordin