      <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>17.661871</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>17.46369</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>17.26551</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>17.06733</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>16.86915</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinates>
            <x>26.017593</x>
            <y>16.67097</y>
            <z>10</z>
          </coordinates>
        </vertex>
        <vertex>
          <coordinat