
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20463931
     no. of nonzeroes in the factor l        =       103277587
     ratio of nonzeroes in factor (min/max)  =          0.8305
     number of super nodes                   =            9118
     maximum order of a front matrix         =            3997
     maximum size of a front matrix          =         7990003
     maximum size of a front trapezoid       =         5084224
     no. of floating point ops for factor    =      1.3139D+11
     no. of floating point ops for solve     =      3.9419D+08
     ratio of flops for factor (min/max)     =          0.9780
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.328125        0.317207
     time (cpu & wall) for ordering          =        0.921105        0.921105
     time (cpu & wall) for other matrix prep =        0.297645        0.287606
     time (cpu & wall) for value input       =        0.265625        0.268266
     time (cpu & wall) for matrix distrib.   =        0.953125        0.975700
     time (cpu & wall) for numeric factor    =        4.593750        4.675766
     computational rate (gflops) for factor  =       28.602024       28.100324
     time (cpu & wall) for numeric solve     =        0.140625        0.136771
     computational rate (gflops) for solve   =        2.803121        2.882119
     effective I/O rate (GB/sec) for solve   =       10.443268       10.737581

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        983040.        8. MB        960475.        7. MB
                95-   1       1245184.       10. MB       1237366.        9. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2197841.       17. MB


  Solver Memory allocated on core    0       =     1084.227 MB
  Solver Memory allocated on core    1       =     1108.050 MB
  Total Solver Memory allocated by all cores =     2192.277 MB





  Performance statistics for DSP solver: icalls =      2

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20453311
     no. of nonzeroes in the factor l        =       104835160
     ratio of nonzeroes in factor (min/max)  =          0.9198
     number of super nodes                   =            9095
     maximum order of a front matrix         =            4153
     maximum size of a front matrix          =         8625781
     maximum size of a front trapezoid       =         5357787
     no. of floating point ops for factor    =      1.3381D+11
     no. of floating point ops for solve     =      4.0044D+08
     ratio of flops for factor (min/max)     =          0.8657
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.359375        0.363579
     time (cpu & wall) for ordering          =        0.938314        0.938314
     time (cpu & wall) for other matrix prep =        0.296061        0.309923
     time (cpu & wall) for value input       =        0.281250        0.283240
     time (cpu & wall) for matrix distrib.   =        0.968750        0.979059
     time (cpu & wall) for numeric factor    =        5.203125        5.231738
     computational rate (gflops) for factor  =       25.718195       25.577538
     time (cpu & wall) for numeric solve     =        0.156250        0.147730
     computational rate (gflops) for solve   =        2.562805        2.710605
     effective I/O rate (GB/sec) for solve   =        9.547949       10.098592

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1212416.        9. MB       1187852.        9. MB
                95-   1       1015808.        8. MB       1006553.        8. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2194405.       17. MB


  Solver Memory allocated on core    0       =     1221.938 MB
  Solver Memory allocated on core    1       =      985.846 MB
  Total Solver Memory allocated by all cores =     2207.785 MB





  Performance statistics for DSP solver: icalls =      3

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20870837
     no. of nonzeroes in the factor l        =       108600452
     ratio of nonzeroes in factor (min/max)  =          0.8557
     number of super nodes                   =            9096
     maximum order of a front matrix         =            3994
     maximum size of a front matrix          =         7978015
     maximum size of a front trapezoid       =         5189928
     no. of floating point ops for factor    =      1.4759D+11
     no. of floating point ops for solve     =      4.1511D+08
     ratio of flops for factor (min/max)     =          0.9360
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.312500        0.315762
     time (cpu & wall) for ordering          =        0.993149        0.993149
     time (cpu & wall) for other matrix prep =        0.303726        0.313089
     time (cpu & wall) for value input       =        0.296875        0.299828
     time (cpu & wall) for matrix distrib.   =        0.937500        0.940232
     time (cpu & wall) for numeric factor    =        5.312500        5.336535
     computational rate (gflops) for factor  =       27.781272       27.656149
     time (cpu & wall) for numeric solve     =        0.156250        0.157368
     computational rate (gflops) for solve   =        2.656676        2.637803
     effective I/O rate (GB/sec) for solve   =        9.897674        9.827362

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1343488.       10. MB       1316160.       10. MB
                95-   1        884736.        7. MB        883777.        7. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2199937.       17. MB


  Solver Memory allocated on core    0       =     1276.791 MB
  Solver Memory allocated on core    1       =     1004.378 MB
  Total Solver Memory allocated by all cores =     2281.169 MB





  Performance statistics for DSP solver: icalls =      4

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20578025
     no. of nonzeroes in the factor l        =       105894313
     ratio of nonzeroes in factor (min/max)  =          0.9974
     number of super nodes                   =            9058
     maximum order of a front matrix         =            4156
     maximum size of a front matrix          =         8638246
     maximum size of a front trapezoid       =         5213442
     no. of floating point ops for factor    =      1.4034D+11
     no. of floating point ops for solve     =      4.0455D+08
     ratio of flops for factor (min/max)     =          0.9034
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.296875        0.301926
     time (cpu & wall) for ordering          =        0.909737        0.909737
     time (cpu & wall) for other matrix prep =        0.293388        0.286730
     time (cpu & wall) for value input       =        0.250000        0.254307
     time (cpu & wall) for matrix distrib.   =        0.890625        0.887812
     time (cpu & wall) for numeric factor    =        5.234375        5.564928
     computational rate (gflops) for factor  =       26.811877       25.219270
     time (cpu & wall) for numeric solve     =        0.171875        0.175290
     computational rate (gflops) for solve   =        2.353732        2.307876
     effective I/O rate (GB/sec) for solve   =        8.769030        8.598190

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1146880.        9. MB       1117011.        9. MB
                95-   1       1081344.        8. MB       1076131.        8. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2193142.       17. MB


  Solver Memory allocated on core    0       =     1181.044 MB
  Solver Memory allocated on core    1       =     1078.352 MB
  Total Solver Memory allocated by all cores =     2259.397 MB





  Performance statistics for DSP solver: icalls =      5

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20440364
     no. of nonzeroes in the factor l        =       107377579
     ratio of nonzeroes in factor (min/max)  =          0.8073
     number of super nodes                   =            9105
     maximum order of a front matrix         =            4493
     maximum size of a front matrix          =        10095771
     maximum size of a front trapezoid       =         7078575
     no. of floating point ops for factor    =      1.5046D+11
     no. of floating point ops for solve     =      4.1030D+08
     ratio of flops for factor (min/max)     =          0.9525
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.343750        0.339849
     time (cpu & wall) for ordering          =        0.917023        0.917023
     time (cpu & wall) for other matrix prep =        0.332977        0.326788
     time (cpu & wall) for value input       =        0.265625        0.270984
     time (cpu & wall) for matrix distrib.   =        1.265625        1.293165
     time (cpu & wall) for numeric factor    =        6.421875        6.510726
     computational rate (gflops) for factor  =       23.429512       23.109773
     time (cpu & wall) for numeric solve     =        0.171875        0.168993
     computational rate (gflops) for solve   =        2.387226        2.427943
     effective I/O rate (GB/sec) for solve   =        8.893816        9.045510

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1409024.       11. MB       1401280.       11. MB
                95-   1        819200.        6. MB        800224.        6. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2201504.       17. MB


  Solver Memory allocated on core    0       =     1284.317 MB
  Solver Memory allocated on core    1       =      975.561 MB
  Total Solver Memory allocated by all cores =     2259.879 MB





  Performance statistics for DSP solver: icalls =      6

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20719293
     no. of nonzeroes in the factor l        =       106304711
     ratio of nonzeroes in factor (min/max)  =          0.7785
     number of super nodes                   =            9100
     maximum order of a front matrix         =            4192
     maximum size of a front matrix          =         8788528
     maximum size of a front trapezoid       =         5076420
     no. of floating point ops for factor    =      1.4328D+11
     no. of floating point ops for solve     =      4.0628D+08
     ratio of flops for factor (min/max)     =          0.9969
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.421875        0.416921
     time (cpu & wall) for ordering          =        1.152000        1.152000
     time (cpu & wall) for other matrix prep =        0.394875        0.435903
     time (cpu & wall) for value input       =        0.296875        0.296721
     time (cpu & wall) for matrix distrib.   =        1.171875        1.177683
     time (cpu & wall) for numeric factor    =        5.859375        6.057183
     computational rate (gflops) for factor  =       24.452594       23.654052
     time (cpu & wall) for numeric solve     =        0.140625        0.146924
     computational rate (gflops) for solve   =        2.889133        2.765260
     effective I/O rate (GB/sec) for solve   =       10.763715       10.302214

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        917504.        7. MB        891113.        7. MB
                95-   1       1310720.       10. MB       1303591.       10. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2194704.       17. MB


  Solver Memory allocated on core    0       =     1084.379 MB
  Solver Memory allocated on core    1       =     1183.899 MB
  Total Solver Memory allocated by all cores =     2268.278 MB





  Performance statistics for DSP solver: icalls =      7

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20717013
     no. of nonzeroes in the factor l        =       104480224
     ratio of nonzeroes in factor (min/max)  =          0.8199
     number of super nodes                   =            9136
     maximum order of a front matrix         =            3673
     maximum size of a front matrix          =         6747301
     maximum size of a front trapezoid       =         5317686
     no. of floating point ops for factor    =      1.3303D+11
     no. of floating point ops for solve     =      3.9874D+08
     ratio of flops for factor (min/max)     =          0.9976
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.390625        0.434238
     time (cpu & wall) for ordering          =        1.028633        1.028633
     time (cpu & wall) for other matrix prep =        0.346367        0.381763
     time (cpu & wall) for value input       =        0.250000        0.245570
     time (cpu & wall) for matrix distrib.   =        0.921875        0.912296
     time (cpu & wall) for numeric factor    =        4.640625        4.694775
     computational rate (gflops) for factor  =       28.667318       28.336669
     time (cpu & wall) for numeric solve     =        0.140625        0.135314
     computational rate (gflops) for solve   =        2.835518        2.946806
     effective I/O rate (GB/sec) for solve   =       10.563968       10.978580

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        851968.        6. MB        840264.        6. MB
                95-   1       1376256.       10. MB       1361305.       10. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2201569.       17. MB


  Solver Memory allocated on core    0       =     1067.878 MB
  Solver Memory allocated on core    1       =     1154.027 MB
  Total Solver Memory allocated by all cores =     2221.905 MB





  Performance statistics for DSP solver: icalls =      8

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20725068
     no. of nonzeroes in the factor l        =       109477897
     ratio of nonzeroes in factor (min/max)  =          0.9907
     number of super nodes                   =            9093
     maximum order of a front matrix         =            4030
     maximum size of a front matrix          =         8122465
     maximum size of a front trapezoid       =         5963151
     no. of floating point ops for factor    =      1.5525D+11
     no. of floating point ops for solve     =      4.1882D+08
     ratio of flops for factor (min/max)     =          0.9671
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.328125        0.339004
     time (cpu & wall) for ordering          =        1.110931        1.110931
     time (cpu & wall) for other matrix prep =        0.170319        0.331165
     time (cpu & wall) for value input       =        0.281250        0.279938
     time (cpu & wall) for matrix distrib.   =        1.125000        1.149413
     time (cpu & wall) for numeric factor    =        6.750000        6.905727
     computational rate (gflops) for factor  =       22.999788       22.481133
     time (cpu & wall) for numeric solve     =        0.171875        0.173022
     computational rate (gflops) for solve   =        2.436758        2.420599
     effective I/O rate (GB/sec) for solve   =        9.078352        9.018151

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1048576.        8. MB       1028884.        8. MB
                95-   1       1179648.        9. MB       1171228.        9. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2200112.       17. MB


  Solver Memory allocated on core    0       =     1214.508 MB
  Solver Memory allocated on core    1       =     1093.676 MB
  Total Solver Memory allocated by all cores =     2308.184 MB





  Performance statistics for DSP solver: icalls =      9

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20717508
     no. of nonzeroes in the factor l        =       105344488
     ratio of nonzeroes in factor (min/max)  =          0.9241
     number of super nodes                   =            9016
     maximum order of a front matrix         =            4123
     maximum size of a front matrix          =         8501626
     maximum size of a front trapezoid       =         5213154
     no. of floating point ops for factor    =      1.3518D+11
     no. of floating point ops for solve     =      4.0245D+08
     ratio of flops for factor (min/max)     =          0.9749
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.343750        0.342199
     time (cpu & wall) for ordering          =        0.937393        0.937393
     time (cpu & wall) for other matrix prep =        0.281357        0.295694
     time (cpu & wall) for value input       =        0.250000        0.254207
     time (cpu & wall) for matrix distrib.   =        0.906250        0.910376
     time (cpu & wall) for numeric factor    =        4.859375        4.986145
     computational rate (gflops) for factor  =       27.817710       27.110462
     time (cpu & wall) for numeric solve     =        0.140625        0.132250
     computational rate (gflops) for solve   =        2.861898        3.043126
     effective I/O rate (GB/sec) for solve   =       10.662248       11.337428

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1277952.       10. MB       1262278.       10. MB
                95-   1        950272.        7. MB        925196.        7. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2187474.       17. MB


  Solver Memory allocated on core    0       =     1235.127 MB
  Solver Memory allocated on core    1       =      988.411 MB
  Total Solver Memory allocated by all cores =     2223.538 MB





  Performance statistics for DSP solver: icalls =     10

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20582164
     no. of nonzeroes in the factor l        =       108426771
     ratio of nonzeroes in factor (min/max)  =          0.8513
     number of super nodes                   =            9056
     maximum order of a front matrix         =            4162
     maximum size of a front matrix          =         8663203
     maximum size of a front trapezoid       =         5358441
     no. of floating point ops for factor    =      1.4910D+11
     no. of floating point ops for solve     =      4.1473D+08
     ratio of flops for factor (min/max)     =          0.9695
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.312500        0.309007
     time (cpu & wall) for ordering          =        0.919785        0.919785
     time (cpu & wall) for other matrix prep =        0.283340        0.290402
     time (cpu & wall) for value input       =        0.234375        0.224392
     time (cpu & wall) for matrix distrib.   =        0.906250        0.896985
     time (cpu & wall) for numeric factor    =        4.796875        4.855988
     computational rate (gflops) for factor  =       31.083634       30.705247
     time (cpu & wall) for numeric solve     =        0.140625        0.137491
     computational rate (gflops) for solve   =        2.949220        3.016447
     effective I/O rate (GB/sec) for solve   =       10.987572       11.238031

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1015808.        8. MB       1012359.        8. MB
                95-   1       1212416.        9. MB       1180237.        9. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2192596.       17. MB


  Solver Memory allocated on core    0       =     1128.983 MB
  Solver Memory allocated on core    1       =     1165.529 MB
  Total Solver Memory allocated by all cores =     2294.512 MB





  Performance statistics for DSP solver: icalls =     11

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20582164
     no. of nonzeroes in the factor l        =       108426771
     ratio of nonzeroes in factor (min/max)  =          0.8513
     number of super nodes                   =            9056
     maximum order of a front matrix         =            4162
     maximum size of a front matrix          =         8663203
     maximum size of a front trapezoid       =         5358441
     no. of floating point ops for factor    =      1.4910D+11
     no. of floating point ops for solve     =      4.1473D+08
     ratio of flops for factor (min/max)     =          0.9695
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.359375        0.360491
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.265625        0.276483
     time (cpu & wall) for matrix distrib.   =        1.078125        1.091445
     time (cpu & wall) for numeric factor    =        5.484375        5.604877
     computational rate (gflops) for factor  =       27.187110       26.602599
     time (cpu & wall) for numeric solve     =        0.156250        0.173235
     computational rate (gflops) for solve   =        2.654298        2.394060
     effective I/O rate (GB/sec) for solve   =        9.888814        8.919275

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1015808.        8. MB       2024974.       15. MB
                95-   1       1212416.        9. MB       2360730.       18. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       4385704.       33. MB


  Solver Memory allocated on core    0       =     1128.983 MB
  Solver Memory allocated on core    1       =     1165.529 MB
  Total Solver Memory allocated by all cores =     2294.512 MB





  Performance statistics for DSP solver: icalls =     12

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20582272
     no. of nonzeroes in the factor l        =       106493348
     ratio of nonzeroes in factor (min/max)  =          0.8784
     number of super nodes                   =            9051
     maximum order of a front matrix         =            4138
     maximum size of a front matrix          =         8563591
     maximum size of a front trapezoid       =         5169900
     no. of floating point ops for factor    =      1.3829D+11
     no. of floating point ops for solve     =      4.0707D+08
     ratio of flops for factor (min/max)     =          0.8842
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.375000        0.373686
     time (cpu & wall) for ordering          =        1.120255        1.120255
     time (cpu & wall) for other matrix prep =        0.379745        0.411623
     time (cpu & wall) for value input       =        0.250000        0.263520
     time (cpu & wall) for matrix distrib.   =        1.062500        1.100836
     time (cpu & wall) for numeric factor    =        5.640625        5.749079
     computational rate (gflops) for factor  =       24.516917       24.054416
     time (cpu & wall) for numeric solve     =        0.140625        0.149925
     computational rate (gflops) for solve   =        2.894714        2.715160
     effective I/O rate (GB/sec) for solve   =       10.784507       10.115564

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1015808.        8. MB       1002621.        8. MB
                95-   1       1212416.        9. MB       1187701.        9. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2190322.       17. MB


  Solver Memory allocated on core    0       =     1128.018 MB
  Solver Memory allocated on core    1       =     1102.620 MB
  Total Solver Memory allocated by all cores =     2230.637 MB





  Performance statistics for DSP solver: icalls =     13

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20582272
     no. of nonzeroes in the factor l        =       106493348
     ratio of nonzeroes in factor (min/max)  =          0.8784
     number of super nodes                   =            9051
     maximum order of a front matrix         =            4138
     maximum size of a front matrix          =         8563591
     maximum size of a front trapezoid       =         5169900
     no. of floating point ops for factor    =      1.3829D+11
     no. of floating point ops for solve     =      4.0707D+08
     ratio of flops for factor (min/max)     =          0.8842
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.218750        0.224851
     time (cpu & wall) for matrix distrib.   =        1.125000        1.238667
     time (cpu & wall) for numeric factor    =        5.125000        5.201230
     computational rate (gflops) for factor  =       26.983559       26.588086
     time (cpu & wall) for numeric solve     =        0.140625        0.158018
     computational rate (gflops) for solve   =        2.894714        2.576091
     effective I/O rate (GB/sec) for solve   =       10.784507        9.597450

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1015808.        8. MB       1002621.        8. MB
                95-   1       1212416.        9. MB       1187701.        9. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2190322.       17. MB


  Solver Memory allocated on core    0       =     1128.018 MB
  Solver Memory allocated on core    1       =     1102.620 MB
  Total Solver Memory allocated by all cores =     2230.637 MB





  Performance statistics for DSP solver: icalls =     14

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20582272
     no. of nonzeroes in the factor l        =       106493348
     ratio of nonzeroes in factor (min/max)  =          0.8784
     number of super nodes                   =            9051
     maximum order of a front matrix         =            4138
     maximum size of a front matrix          =         8563591
     maximum size of a front trapezoid       =         5169900
     no. of floating point ops for factor    =      1.3829D+11
     no. of floating point ops for solve     =      4.0707D+08
     ratio of flops for factor (min/max)     =          0.8842
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.234375        0.231190
     time (cpu & wall) for matrix distrib.   =        1.093750        1.219801
     time (cpu & wall) for numeric factor    =        5.171875        5.338392
     computational rate (gflops) for factor  =       26.738995       25.904945
     time (cpu & wall) for numeric solve     =        0.125000        0.136063
     computational rate (gflops) for solve   =        3.256553        2.991774
     effective I/O rate (GB/sec) for solve   =       12.132570       11.146110

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1015808.        8. MB       1002621.        8. MB
                95-   1       1212416.        9. MB       1187701.        9. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2190322.       17. MB


  Solver Memory allocated on core    0       =     1128.018 MB
  Solver Memory allocated on core    1       =     1102.620 MB
  Total Solver Memory allocated by all cores =     2230.637 MB





  Performance statistics for DSP solver: icalls =     15

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20573631
     no. of nonzeroes in the factor l        =       101344566
     ratio of nonzeroes in factor (min/max)  =          0.9070
     number of super nodes                   =            9111
     maximum order of a front matrix         =            4114
     maximum size of a front matrix          =         8464555
     maximum size of a front trapezoid       =         5122185
     no. of floating point ops for factor    =      1.2018D+11
     no. of floating point ops for solve     =      3.8647D+08
     ratio of flops for factor (min/max)     =          0.9059
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.312500        0.307065
     time (cpu & wall) for ordering          =        0.892258        0.892258
     time (cpu & wall) for other matrix prep =        0.295242        0.289925
     time (cpu & wall) for value input       =        0.250000        0.247579
     time (cpu & wall) for matrix distrib.   =        0.859375        0.862804
     time (cpu & wall) for numeric factor    =        4.671875        4.813759
     computational rate (gflops) for factor  =       25.724427       24.966206
     time (cpu & wall) for numeric solve     =        0.140625        0.143964
     computational rate (gflops) for solve   =        2.748246        2.684501
     effective I/O rate (GB/sec) for solve   =       10.238828       10.001337

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1310720.       10. MB       1297867.       10. MB
                95-   1        917504.        7. MB        898409.        7. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2196276.       17. MB


  Solver Memory allocated on core    0       =     1202.715 MB
  Solver Memory allocated on core    1       =      966.672 MB
  Total Solver Memory allocated by all cores =     2169.387 MB





  Performance statistics for DSP solver: icalls =     16

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20573631
     no. of nonzeroes in the factor l        =       101344566
     ratio of nonzeroes in factor (min/max)  =          0.9070
     number of super nodes                   =            9111
     maximum order of a front matrix         =            4114
     maximum size of a front matrix          =         8464555
     maximum size of a front trapezoid       =         5122185
     no. of floating point ops for factor    =      1.2018D+11
     no. of floating point ops for solve     =      3.8647D+08
     ratio of flops for factor (min/max)     =          0.9059
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.234375        0.232603
     time (cpu & wall) for matrix distrib.   =        0.890625        0.889596
     time (cpu & wall) for numeric factor    =        4.406250        4.441802
     computational rate (gflops) for factor  =       27.275190       27.056883
     time (cpu & wall) for numeric solve     =        0.140625        0.143123
     computational rate (gflops) for solve   =        2.748246        2.700281
     effective I/O rate (GB/sec) for solve   =       10.238828       10.060130

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1310720.       10. MB       1297867.       10. MB
                95-   1        917504.        7. MB        898409.        7. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2196276.       17. MB


  Solver Memory allocated on core    0       =     1202.715 MB
  Solver Memory allocated on core    1       =      966.672 MB
  Total Solver Memory allocated by all cores =     2169.387 MB





  Performance statistics for DSP solver: icalls =     17

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20563668
     no. of nonzeroes in the factor l        =       108193593
     ratio of nonzeroes in factor (min/max)  =          0.7379
     number of super nodes                   =            9085
     maximum order of a front matrix         =            3874
     maximum size of a front matrix          =         7505875
     maximum size of a front trapezoid       =         5057997
     no. of floating point ops for factor    =      1.4599D+11
     no. of floating point ops for solve     =      4.1384D+08
     ratio of flops for factor (min/max)     =          0.9544
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.296875        0.312747
     time (cpu & wall) for ordering          =        0.977173        0.977173
     time (cpu & wall) for other matrix prep =        0.288452        0.306997
     time (cpu & wall) for value input       =        0.296875        0.293437
     time (cpu & wall) for matrix distrib.   =        1.093750        1.094936
     time (cpu & wall) for numeric factor    =        6.109375        6.165469
     computational rate (gflops) for factor  =       23.895380       23.677977
     time (cpu & wall) for numeric solve     =        0.171875        0.170020
     computational rate (gflops) for solve   =        2.407818        2.434086
     effective I/O rate (GB/sec) for solve   =        8.970534        9.068397

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1441792.       11. MB       1428354.       11. MB
                95-   1        786432.        6. MB        765789.        6. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2194143.       17. MB


  Solver Memory allocated on core    0       =     1338.843 MB
  Solver Memory allocated on core    1       =      916.626 MB
  Total Solver Memory allocated by all cores =     2255.469 MB





  Performance statistics for DSP solver: icalls =     18

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20563668
     no. of nonzeroes in the factor l        =       108193593
     ratio of nonzeroes in factor (min/max)  =          0.7379
     number of super nodes                   =            9085
     maximum order of a front matrix         =            3874
     maximum size of a front matrix          =         7505875
     maximum size of a front trapezoid       =         5057997
     no. of floating point ops for factor    =      1.4599D+11
     no. of floating point ops for solve     =      4.1384D+08
     ratio of flops for factor (min/max)     =          0.9544
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.375000        0.382270
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.312500        0.313717
     time (cpu & wall) for matrix distrib.   =        1.187500        1.194953
     time (cpu & wall) for numeric factor    =        5.937500        6.175941
     computational rate (gflops) for factor  =       24.587089       23.637831
     time (cpu & wall) for numeric solve     =        0.156250        0.149689
     computational rate (gflops) for solve   =        2.648600        2.764684
     effective I/O rate (GB/sec) for solve   =        9.867587       10.300068

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1441792.       11. MB       1428354.       11. MB
                95-   1        786432.        6. MB        765789.        6. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2194143.       17. MB


  Solver Memory allocated on core    0       =     1338.794 MB
  Solver Memory allocated on core    1       =      916.626 MB
  Total Solver Memory allocated by all cores =     2255.420 MB





  Performance statistics for DSP solver: icalls =     19

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20420099
     no. of nonzeroes in the factor l        =       107256615
     ratio of nonzeroes in factor (min/max)  =          0.7603
     number of super nodes                   =            9115
     maximum order of a front matrix         =            4063
     maximum size of a front matrix          =         8256016
     maximum size of a front trapezoid       =         5899959
     no. of floating point ops for factor    =      1.4469D+11
     no. of floating point ops for solve     =      4.0995D+08
     ratio of flops for factor (min/max)     =          0.9616
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.375000        0.373382
     time (cpu & wall) for ordering          =        1.159454        1.159454
     time (cpu & wall) for other matrix prep =        0.356171        0.356585
     time (cpu & wall) for value input       =        0.250000        0.252125
     time (cpu & wall) for matrix distrib.   =        1.218750        1.317949
     time (cpu & wall) for numeric factor    =        6.187500        6.656817
     computational rate (gflops) for factor  =       23.384532       21.735881
     time (cpu & wall) for numeric solve     =        0.140625        0.138787
     computational rate (gflops) for solve   =        2.915215        2.953826
     effective I/O rate (GB/sec) for solve   =       10.860883       11.004734

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        917504.        7. MB        913544.        7. MB
                95-   1       1310720.       10. MB       1287513.       10. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2201057.       17. MB


  Solver Memory allocated on core    0       =     1060.792 MB
  Solver Memory allocated on core    1       =     1195.575 MB
  Total Solver Memory allocated by all cores =     2256.366 MB





  Performance statistics for DSP solver: icalls =     20

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20421689
     no. of nonzeroes in the factor l        =       108706270
     ratio of nonzeroes in factor (min/max)  =          0.9012
     number of super nodes                   =            9040
     maximum order of a front matrix         =            4273
     maximum size of a front matrix          =         9131401
     maximum size of a front trapezoid       =         5737179
     no. of floating point ops for factor    =      1.5246D+11
     no. of floating point ops for solve     =      4.1575D+08
     ratio of flops for factor (min/max)     =          0.9704
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.343750        0.351065
     time (cpu & wall) for ordering          =        1.267456        1.267456
     time (cpu & wall) for other matrix prep =        0.326294        0.359682
     time (cpu & wall) for value input       =        0.296875        0.323906
     time (cpu & wall) for matrix distrib.   =        1.156250        1.188923
     time (cpu & wall) for numeric factor    =        6.296875        6.551897
     computational rate (gflops) for factor  =       24.212050       23.269636
     time (cpu & wall) for numeric solve     =        0.187500        0.187632
     computational rate (gflops) for solve   =        2.217320        2.215765
     effective I/O rate (GB/sec) for solve   =        8.260818        8.255024

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1310720.       10. MB       1279298.       10. MB
                95-   1        917504.        7. MB        915157.        7. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2194455.       17. MB


  Solver Memory allocated on core    0       =     1252.336 MB
  Solver Memory allocated on core    1       =     1026.295 MB
  Total Solver Memory allocated by all cores =     2278.631 MB





  Performance statistics for DSP solver: icalls =     21

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20423243
     no. of nonzeroes in the factor l        =       103823531
     ratio of nonzeroes in factor (min/max)  =          0.6981
     number of super nodes                   =            9037
     maximum order of a front matrix         =            4141
     maximum size of a front matrix          =         8576011
     maximum size of a front trapezoid       =         5162931
     no. of floating point ops for factor    =      1.3041D+11
     no. of floating point ops for solve     =      3.9621D+08
     ratio of flops for factor (min/max)     =          0.9279
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.406250        0.400202
     time (cpu & wall) for ordering          =        1.213867        1.213867
     time (cpu & wall) for other matrix prep =        0.411133        0.414567
     time (cpu & wall) for value input       =        0.265625        0.270194
     time (cpu & wall) for matrix distrib.   =        1.171875        1.220217
     time (cpu & wall) for numeric factor    =        5.062500        5.174145
     computational rate (gflops) for factor  =       25.760691       25.204842
     time (cpu & wall) for numeric solve     =        0.171875        0.175233
     computational rate (gflops) for solve   =        2.305196        2.261027
     effective I/O rate (GB/sec) for solve   =        8.588205        8.423650

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        688128.        5. MB        672615.        5. MB
                95-   1       1540096.       12. MB       1516422.       12. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2189037.       17. MB


  Solver Memory allocated on core    0       =      990.195 MB
  Solver Memory allocated on core    1       =     1205.148 MB
  Total Solver Memory allocated by all cores =     2195.344 MB





  Performance statistics for DSP solver: icalls =     22

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20423243
     no. of nonzeroes in the factor l        =       103823531
     ratio of nonzeroes in factor (min/max)  =          0.6981
     number of super nodes                   =            9037
     maximum order of a front matrix         =            4141
     maximum size of a front matrix          =         8576011
     maximum size of a front trapezoid       =         5162931
     no. of floating point ops for factor    =      1.3041D+11
     no. of floating point ops for solve     =      3.9621D+08
     ratio of flops for factor (min/max)     =          0.9279
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.296875        0.303088
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.281250        0.277065
     time (cpu & wall) for matrix distrib.   =        1.203125        1.210979
     time (cpu & wall) for numeric factor    =        4.781250        4.924550
     computational rate (gflops) for factor  =       27.276026       26.482317
     time (cpu & wall) for numeric solve     =        0.156250        0.151540
     computational rate (gflops) for solve   =        2.535715        2.614530
     effective I/O rate (GB/sec) for solve   =        9.447025        9.740655

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        688128.        5. MB        672615.        5. MB
                95-   1       1540096.       12. MB       1516422.       12. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2189037.       17. MB


  Solver Memory allocated on core    0       =      990.195 MB
  Solver Memory allocated on core    1       =     1205.148 MB
  Total Solver Memory allocated by all cores =     2195.344 MB





  Performance statistics for DSP solver: icalls =     23

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20428094
     no. of nonzeroes in the factor l        =       106756230
     ratio of nonzeroes in factor (min/max)  =          0.8737
     number of super nodes                   =            9150
     maximum order of a front matrix         =            4222
     maximum size of a front matrix          =         8914753
     maximum size of a front trapezoid       =         6020187
     no. of floating point ops for factor    =      1.4410D+11
     no. of floating point ops for solve     =      4.0796D+08
     ratio of flops for factor (min/max)     =          0.9253
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.375000        0.371423
     time (cpu & wall) for ordering          =        1.028137        1.028137
     time (cpu & wall) for other matrix prep =        0.315613        0.305828
     time (cpu & wall) for value input       =        0.218750        0.230418
     time (cpu & wall) for matrix distrib.   =        1.015625        1.036990
     time (cpu & wall) for numeric factor    =        5.187500        5.282277
     computational rate (gflops) for factor  =       27.777793       27.279391
     time (cpu & wall) for numeric solve     =        0.156250        0.165008
     computational rate (gflops) for solve   =        2.610931        2.472356
     effective I/O rate (GB/sec) for solve   =        9.727247        9.210977

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1310720.       10. MB       1298874.       10. MB
                95-   1        917504.        7. MB        904604.        7. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2203478.       17. MB


  Solver Memory allocated on core    0       =     1265.367 MB
  Solver Memory allocated on core    1       =     1001.700 MB
  Total Solver Memory allocated by all cores =     2267.067 MB





  Performance statistics for DSP solver: icalls =     24

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20424860
     no. of nonzeroes in the factor l        =       107870670
     ratio of nonzeroes in factor (min/max)  =          0.8363
     number of super nodes                   =            9057
     maximum order of a front matrix         =            4577
     maximum size of a front matrix          =        10476753
     maximum size of a front trapezoid       =         7400313
     no. of floating point ops for factor    =      1.5314D+11
     no. of floating point ops for solve     =      4.1232D+08
     ratio of flops for factor (min/max)     =          0.9405
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.453125        0.477366
     time (cpu & wall) for ordering          =        1.123108        1.123108
     time (cpu & wall) for other matrix prep =        0.361267        0.421230
     time (cpu & wall) for value input       =        0.218750        0.218590
     time (cpu & wall) for matrix distrib.   =        0.875000        0.898387
     time (cpu & wall) for numeric factor    =        5.625000        5.798591
     computational rate (gflops) for factor  =       27.224346       26.409339
     time (cpu & wall) for numeric solve     =        0.140625        0.146939
     computational rate (gflops) for solve   =        2.932039        2.806043
     effective I/O rate (GB/sec) for solve   =       10.923562       10.454154

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1081344.        8. MB       1057155.        8. MB
                95-   1       1146880.        9. MB       1138691.        9. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2195846.       17. MB


  Solver Memory allocated on core    0       =     1127.660 MB
  Solver Memory allocated on core    1       =     1149.263 MB
  Total Solver Memory allocated by all cores =     2276.923 MB





  Performance statistics for DSP solver: icalls =     25

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20428202
     no. of nonzeroes in the factor l        =       104653816
     ratio of nonzeroes in factor (min/max)  =          0.6870
     number of super nodes                   =            9123
     maximum order of a front matrix         =            4165
     maximum size of a front matrix          =         8675695
     maximum size of a front trapezoid       =         5410266
     no. of floating point ops for factor    =      1.3253D+11
     no. of floating point ops for solve     =      3.9937D+08
     ratio of flops for factor (min/max)     =          0.9320
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.312500        0.306094
     time (cpu & wall) for ordering          =        0.903809        0.903809
     time (cpu & wall) for other matrix prep =        0.299316        0.291853
     time (cpu & wall) for value input       =        0.203125        0.204045
     time (cpu & wall) for matrix distrib.   =        1.062500        1.067822
     time (cpu & wall) for numeric factor    =        4.703125        4.716485
     computational rate (gflops) for factor  =       28.179387       28.099567
     time (cpu & wall) for numeric solve     =        0.140625        0.138208
     computational rate (gflops) for solve   =        2.839956        2.889626
     effective I/O rate (GB/sec) for solve   =       10.580502       10.765551

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        786432.        6. MB        755569.        6. MB
                95-   1       1474560.       11. MB       1445559.       11. MB

                -------     ----------     --------     ----------     --------
                Totals:       2260992.       17. MB       2201128.       17. MB


  Solver Memory allocated on core    0       =      993.394 MB
  Solver Memory allocated on core    1       =     1210.149 MB
  Total Solver Memory allocated by all cores =     2203.543 MB





  Performance statistics for DSP solver: icalls =     26

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20463931
     no. of nonzeroes in the factor l        =       103277587
     ratio of nonzeroes in factor (min/max)  =          0.8305
     number of super nodes                   =            9118
     maximum order of a front matrix         =            3997
     maximum size of a front matrix          =         7990003
     maximum size of a front trapezoid       =         5084224
     no. of floating point ops for factor    =      1.3139D+11
     no. of floating point ops for solve     =      3.9419D+08
     ratio of flops for factor (min/max)     =          0.9780
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.312500        0.310147
     time (cpu & wall) for ordering          =        0.842834        0.842834
     time (cpu & wall) for other matrix prep =        0.282166        0.290523
     time (cpu & wall) for value input       =        0.296875        0.290934
     time (cpu & wall) for matrix distrib.   =        0.953125        0.952285
     time (cpu & wall) for numeric factor    =        4.843750        5.061146
     computational rate (gflops) for factor  =       27.125791       25.960633
     time (cpu & wall) for numeric solve     =        0.140625        0.142759
     computational rate (gflops) for solve   =        2.803121        2.761219
     effective I/O rate (GB/sec) for solve   =       10.443268       10.287158

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        983040.        8. MB        960475.        7. MB
                95-   1       1245184.       10. MB       1237366.        9. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2197841.       17. MB


  Solver Memory allocated on core    0       =     1084.227 MB
  Solver Memory allocated on core    1       =     1108.050 MB
  Total Solver Memory allocated by all cores =     2192.277 MB





  Performance statistics for DSP solver: icalls =     27

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20519446
     no. of nonzeroes in the factor l        =       105140866
     ratio of nonzeroes in factor (min/max)  =          0.9646
     number of super nodes                   =            9075
     maximum order of a front matrix         =            4545
     maximum size of a front matrix          =        10330785
     maximum size of a front trapezoid       =         7251864
     no. of floating point ops for factor    =      1.4094D+11
     no. of floating point ops for solve     =      4.0146D+08
     ratio of flops for factor (min/max)     =          0.9985
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.328125        0.319548
     time (cpu & wall) for ordering          =        0.855957        0.855957
     time (cpu & wall) for other matrix prep =        0.300293        0.299778
     time (cpu & wall) for value input       =        0.375000        0.387927
     time (cpu & wall) for matrix distrib.   =        1.171875        1.191268
     time (cpu & wall) for numeric factor    =        5.703125        5.862301
     computational rate (gflops) for factor  =       24.712649       24.041640
     time (cpu & wall) for numeric solve     =        0.125000        0.134753
     computational rate (gflops) for solve   =        3.211657        2.979211
     effective I/O rate (GB/sec) for solve   =       11.965306       11.099307

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1048576.        8. MB       1043702.        8. MB
                95-   1       1179648.        9. MB       1154117.        9. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2197819.       17. MB


  Solver Memory allocated on core    0       =     1148.868 MB
  Solver Memory allocated on core    1       =     1065.873 MB
  Total Solver Memory allocated by all cores =     2214.741 MB





  Performance statistics for DSP solver: icalls =     28

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20768594
     no. of nonzeroes in the factor l        =       104860708
     ratio of nonzeroes in factor (min/max)  =          0.7820
     number of super nodes                   =            9103
     maximum order of a front matrix         =            4186
     maximum size of a front matrix          =         8763391
     maximum size of a front trapezoid       =         5244057
     no. of floating point ops for factor    =      1.3752D+11
     no. of floating point ops for solve     =      4.0046D+08
     ratio of flops for factor (min/max)     =          0.9929
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             169
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.343750        0.368330
     time (cpu & wall) for ordering          =        0.993958        0.993958
     time (cpu & wall) for other matrix prep =        0.271667        0.358820
     time (cpu & wall) for value input       =        0.375000        0.372704
     time (cpu & wall) for matrix distrib.   =        1.125000        1.137546
     time (cpu & wall) for numeric factor    =        5.734375        5.865404
     computational rate (gflops) for factor  =       23.980958       23.445241
     time (cpu & wall) for numeric solve     =        0.171875        0.179655
     computational rate (gflops) for solve   =        2.329966        2.229061
     effective I/O rate (GB/sec) for solve   =        8.680489        8.304559

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        950272.        7. MB        945516.        7. MB
                95-   1       1277952.       10. MB       1252452.       10. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2197968.       17. MB


  Solver Memory allocated on core    0       =     1092.039 MB
  Solver Memory allocated on core    1       =     1167.702 MB
  Total Solver Memory allocated by all cores =     2259.740 MB





  Performance statistics for DSP solver: icalls =     29

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20465318
     no. of nonzeroes in the factor l        =       105684883
     ratio of nonzeroes in factor (min/max)  =          0.8536
     number of super nodes                   =            9087
     maximum order of a front matrix         =            4057
     maximum size of a front matrix          =         8231653
     maximum size of a front trapezoid       =         5312970
     no. of floating point ops for factor    =      1.4110D+11
     no. of floating point ops for solve     =      4.0369D+08
     ratio of flops for factor (min/max)     =          0.9052
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.328125        0.318028
     time (cpu & wall) for ordering          =        1.206696        1.206696
     time (cpu & wall) for other matrix prep =        0.246429        0.308792
     time (cpu & wall) for value input       =        0.218750        0.221801
     time (cpu & wall) for matrix distrib.   =        0.906250        0.907434
     time (cpu & wall) for numeric factor    =        5.171875        5.303413
     computational rate (gflops) for factor  =       27.282610       26.605935
     time (cpu & wall) for numeric solve     =        0.140625        0.140334
     computational rate (gflops) for solve   =        2.870660        2.876611
     effective I/O rate (GB/sec) for solve   =       10.694892       10.717063

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1245184.       10. MB       1218883.        9. MB
                95-   1        983040.        8. MB        978380.        7. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2197263.       17. MB


  Solver Memory allocated on core    0       =     1242.809 MB
  Solver Memory allocated on core    1       =      969.124 MB
  Total Solver Memory allocated by all cores =     2211.933 MB





  Performance statistics for DSP solver: icalls =     30

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20716203
     no. of nonzeroes in the factor l        =       105590204
     ratio of nonzeroes in factor (min/max)  =          0.9124
     number of super nodes                   =            9068
     maximum order of a front matrix         =            4423
     maximum size of a front matrix          =         9783676
     maximum size of a front trapezoid       =         6287055
     no. of floating point ops for factor    =      1.3744D+11
     no. of floating point ops for solve     =      4.0319D+08
     ratio of flops for factor (min/max)     =          0.9059
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.359375        0.354558
     time (cpu & wall) for ordering          =        1.060303        1.060303
     time (cpu & wall) for other matrix prep =        0.299072        0.322382
     time (cpu & wall) for value input       =        0.312500        0.310999
     time (cpu & wall) for matrix distrib.   =        0.953125        0.953281
     time (cpu & wall) for numeric factor    =        5.500000        5.624892
     computational rate (gflops) for factor  =       24.989147       24.434302
     time (cpu & wall) for numeric solve     =        0.140625        0.143454
     computational rate (gflops) for solve   =        2.867156        2.810613
     effective I/O rate (GB/sec) for solve   =       10.681835       10.471182

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1146880.        9. MB       1136070.        9. MB
                95-   1       1081344.        8. MB       1061216.        8. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2197286.       17. MB


  Solver Memory allocated on core    0       =     1169.245 MB
  Solver Memory allocated on core    1       =     1060.272 MB
  Total Solver Memory allocated by all cores =     2229.517 MB





  Performance statistics for DSP solver: icalls =     31

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20716203
     no. of nonzeroes in the factor l        =       105590204
     ratio of nonzeroes in factor (min/max)  =          0.9124
     number of super nodes                   =            9068
     maximum order of a front matrix         =            4423
     maximum size of a front matrix          =         9783676
     maximum size of a front trapezoid       =         6287055
     no. of floating point ops for factor    =      1.3744D+11
     no. of floating point ops for solve     =      4.0319D+08
     ratio of flops for factor (min/max)     =          0.9059
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.343750        0.348847
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.265625        0.262647
     time (cpu & wall) for matrix distrib.   =        0.937500        0.970845
     time (cpu & wall) for numeric factor    =        5.062500        5.159173
     computational rate (gflops) for factor  =       27.148703       26.639987
     time (cpu & wall) for numeric solve     =        0.125000        0.134385
     computational rate (gflops) for solve   =        3.225550        3.000287
     effective I/O rate (GB/sec) for solve   =       12.017065       11.177827

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1146880.        9. MB       1136070.        9. MB
                95-   1       1081344.        8. MB       1061216.        8. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2197286.       17. MB


  Solver Memory allocated on core    0       =     1169.221 MB
  Solver Memory allocated on core    1       =     1060.272 MB
  Total Solver Memory allocated by all cores =     2229.493 MB





  Performance statistics for DSP solver: icalls =     32

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20701065
     no. of nonzeroes in the factor l        =       105566361
     ratio of nonzeroes in factor (min/max)  =          0.9928
     number of super nodes                   =            9074
     maximum order of a front matrix         =            3827
     maximum size of a front matrix          =         7324878
     maximum size of a front trapezoid       =         5581134
     no. of floating point ops for factor    =      1.3574D+11
     no. of floating point ops for solve     =      4.0325D+08
     ratio of flops for factor (min/max)     =          0.9547
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.390625        0.391517
     time (cpu & wall) for ordering          =        1.012268        1.012268
     time (cpu & wall) for other matrix prep =        0.300232        0.354704
     time (cpu & wall) for value input       =        0.265625        0.259585
     time (cpu & wall) for matrix distrib.   =        1.015625        1.016918
     time (cpu & wall) for numeric factor    =        4.750000        4.817389
     computational rate (gflops) for factor  =       28.577626       28.177862
     time (cpu & wall) for numeric solve     =        0.140625        0.140709
     computational rate (gflops) for solve   =        2.867588        2.865886
     effective I/O rate (GB/sec) for solve   =       10.683447       10.677104

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1048576.        8. MB       1017187.        8. MB
                95-   1       1179648.        9. MB       1178229.        9. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2195416.       17. MB


  Solver Memory allocated on core    0       =     1173.539 MB
  Solver Memory allocated on core    1       =     1049.584 MB
  Total Solver Memory allocated by all cores =     2223.123 MB





  Performance statistics for DSP solver: icalls =     33

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20701065
     no. of nonzeroes in the factor l        =       105566361
     ratio of nonzeroes in factor (min/max)  =          0.9928
     number of super nodes                   =            9074
     maximum order of a front matrix         =            3827
     maximum size of a front matrix          =         7324878
     maximum size of a front trapezoid       =         5581134
     no. of floating point ops for factor    =      1.3574D+11
     no. of floating point ops for solve     =      4.0325D+08
     ratio of flops for factor (min/max)     =          0.9547
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.359375        0.388547
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.281250        0.298595
     time (cpu & wall) for matrix distrib.   =        1.125000        1.127752
     time (cpu & wall) for numeric factor    =        6.000000        6.497077
     computational rate (gflops) for factor  =       22.623954       20.893044
     time (cpu & wall) for numeric solve     =        0.171875        0.175147
     computational rate (gflops) for solve   =        2.346209        2.302385
     effective I/O rate (GB/sec) for solve   =        8.741002        8.577732

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1048576.        8. MB       1017187.        8. MB
                95-   1       1179648.        9. MB       1178229.        9. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2195416.       17. MB


  Solver Memory allocated on core    0       =     1173.542 MB
  Solver Memory allocated on core    1       =     1049.584 MB
  Total Solver Memory allocated by all cores =     2223.125 MB





  Performance statistics for DSP solver: icalls =     34

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20701371
     no. of nonzeroes in the factor l        =       108056423
     ratio of nonzeroes in factor (min/max)  =          0.6620
     number of super nodes                   =            9041
     maximum order of a front matrix         =            4151
     maximum size of a front matrix          =         8617476
     maximum size of a front trapezoid       =         5110620
     no. of floating point ops for factor    =      1.4565D+11
     no. of floating point ops for solve     =      4.1311D+08
     ratio of flops for factor (min/max)     =          0.9703
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.343750        0.361955
     time (cpu & wall) for ordering          =        1.146179        1.146179
     time (cpu & wall) for other matrix prep =        0.338196        0.369508
     time (cpu & wall) for value input       =        0.281250        0.303638
     time (cpu & wall) for matrix distrib.   =        1.109375        1.106764
     time (cpu & wall) for numeric factor    =        5.515625        5.654827
     computational rate (gflops) for factor  =       26.406286       25.756254
     time (cpu & wall) for numeric solve     =        0.171875        0.202924
     computational rate (gflops) for solve   =        2.403567        2.035800
     effective I/O rate (GB/sec) for solve   =        8.954696        7.584547

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        688128.        5. MB        661374.        5. MB
                95-   1       1540096.       12. MB       1529065.       12. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2190439.       17. MB


  Solver Memory allocated on core    0       =     1002.017 MB
  Solver Memory allocated on core    1       =     1258.410 MB
  Total Solver Memory allocated by all cores =     2260.427 MB





  Performance statistics for DSP solver: icalls =     35

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20701236
     no. of nonzeroes in the factor l        =       105587884
     ratio of nonzeroes in factor (min/max)  =          0.7740
     number of super nodes                   =            9038
     maximum order of a front matrix         =            4195
     maximum size of a front matrix          =         8801110
     maximum size of a front trapezoid       =         5247165
     no. of floating point ops for factor    =      1.3741D+11
     no. of floating point ops for solve     =      4.0344D+08
     ratio of flops for factor (min/max)     =          0.9491
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.281250        0.304045
     time (cpu & wall) for ordering          =        0.910767        0.910767
     time (cpu & wall) for other matrix prep =        0.307983        0.297314
     time (cpu & wall) for value input       =        0.250000        0.251813
     time (cpu & wall) for matrix distrib.   =        0.953125        0.957262
     time (cpu & wall) for numeric factor    =        4.437500        4.486030
     computational rate (gflops) for factor  =       30.966736       30.631735
     time (cpu & wall) for numeric solve     =        0.140625        0.139472
     computational rate (gflops) for solve   =        2.868936        2.892662
     effective I/O rate (GB/sec) for solve   =       10.688466       10.776860

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        819200.        6. MB        791460.        6. MB
                95-   1       1409024.       11. MB       1396830.       11. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2188290.       17. MB


  Solver Memory allocated on core    0       =     1079.967 MB
  Solver Memory allocated on core    1       =     1155.807 MB
  Total Solver Memory allocated by all cores =     2235.774 MB





  Performance statistics for DSP solver: icalls =     36

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20694648
     no. of nonzeroes in the factor l        =       105310251
     ratio of nonzeroes in factor (min/max)  =          0.8969
     number of super nodes                   =            9078
     maximum order of a front matrix         =            4614
     maximum size of a front matrix          =        10646805
     maximum size of a front trapezoid       =         7567884
     no. of floating point ops for factor    =      1.4235D+11
     no. of floating point ops for solve     =      4.0182D+08
     ratio of flops for factor (min/max)     =          0.9390
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.328125        0.324955
     time (cpu & wall) for ordering          =        0.873535        0.873535
     time (cpu & wall) for other matrix prep =        0.298340        0.292019
     time (cpu & wall) for value input       =        0.250000        0.252156
     time (cpu & wall) for matrix distrib.   =        0.937500        0.926874
     time (cpu & wall) for numeric factor    =        4.750000        4.774729
     computational rate (gflops) for factor  =       29.969314       29.814098
     time (cpu & wall) for numeric solve     =        0.140625        0.136358
     computational rate (gflops) for solve   =        2.857396        2.946812
     effective I/O rate (GB/sec) for solve   =       10.645475       10.978603

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        851968.        6. MB        849248.        6. MB
                95-   1       1376256.       10. MB       1347391.       10. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2196639.       17. MB


  Solver Memory allocated on core    0       =     1136.462 MB
  Solver Memory allocated on core    1       =     1108.075 MB
  Total Solver Memory allocated by all cores =     2244.538 MB





  Performance statistics for DSP solver: icalls =     37

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20694603
     no. of nonzeroes in the factor l        =       106591034
     ratio of nonzeroes in factor (min/max)  =          0.9615
     number of super nodes                   =            9074
     maximum order of a front matrix         =            4186
     maximum size of a front matrix          =         8763391
     maximum size of a front trapezoid       =         5864388
     no. of floating point ops for factor    =      1.4243D+11
     no. of floating point ops for solve     =      4.0735D+08
     ratio of flops for factor (min/max)     =          0.9602
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.328125        0.323583
     time (cpu & wall) for ordering          =        0.882446        0.882446
     time (cpu & wall) for other matrix prep =        0.351929        0.341766
     time (cpu & wall) for value input       =        0.265625        0.271103
     time (cpu & wall) for matrix distrib.   =        1.031250        1.028986
     time (cpu & wall) for numeric factor    =        5.125000        5.190904
     computational rate (gflops) for factor  =       27.792142       27.439290
     time (cpu & wall) for numeric solve     =        0.140625        0.186136
     computational rate (gflops) for solve   =        2.896719        2.188457
     effective I/O rate (GB/sec) for solve   =       10.791974        8.153286

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1245184.       10. MB       1235712.        9. MB
                95-   1        983040.        8. MB        959387.        7. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2195099.       17. MB


  Solver Memory allocated on core    0       =     1213.892 MB
  Solver Memory allocated on core    1       =     1012.985 MB
  Total Solver Memory allocated by all cores =     2226.877 MB





  Performance statistics for DSP solver: icalls =     38

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20694648
     no. of nonzeroes in the factor l        =       105310251
     ratio of nonzeroes in factor (min/max)  =          0.8969
     number of super nodes                   =            9078
     maximum order of a front matrix         =            4614
     maximum size of a front matrix          =        10646805
     maximum size of a front trapezoid       =         7567884
     no. of floating point ops for factor    =      1.4235D+11
     no. of floating point ops for solve     =      4.0182D+08
     ratio of flops for factor (min/max)     =          0.9390
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.328125        0.320592
     time (cpu & wall) for ordering          =        1.097107        1.097107
     time (cpu & wall) for other matrix prep =        0.371643        0.434313
     time (cpu & wall) for value input       =        0.296875        0.306954
     time (cpu & wall) for matrix distrib.   =        1.140625        1.209193
     time (cpu & wall) for numeric factor    =        6.250000        6.995556
     computational rate (gflops) for factor  =       22.776678       20.349238
     time (cpu & wall) for numeric solve     =        0.218750        0.282044
     computational rate (gflops) for solve   =        1.836897        1.424678
     effective I/O rate (GB/sec) for solve   =        6.843519        5.307759

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        851968.        6. MB        849248.        6. MB
                95-   1       1376256.       10. MB       1347391.       10. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2196639.       17. MB


  Solver Memory allocated on core    0       =     1136.462 MB
  Solver Memory allocated on core    1       =     1108.075 MB
  Total Solver Memory allocated by all cores =     2244.538 MB





  Performance statistics for DSP solver: icalls =     39

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20702838
     no. of nonzeroes in the factor l        =       108802681
     ratio of nonzeroes in factor (min/max)  =          0.6337
     number of super nodes                   =            9095
     maximum order of a front matrix         =            4557
     maximum size of a front matrix          =        10385403
     maximum size of a front trapezoid       =         7306482
     no. of floating point ops for factor    =      1.5445D+11
     no. of floating point ops for solve     =      4.1564D+08
     ratio of flops for factor (min/max)     =          0.9208
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.328125        0.326632
     time (cpu & wall) for ordering          =        0.955872        0.955872
     time (cpu & wall) for other matrix prep =        0.341003        0.329053
     time (cpu & wall) for value input       =        0.359375        0.351839
     time (cpu & wall) for matrix distrib.   =        1.046875        1.074407
     time (cpu & wall) for numeric factor    =        5.421875        5.827463
     computational rate (gflops) for factor  =       28.486576       26.503926
     time (cpu & wall) for numeric solve     =        0.171875        0.168120
     computational rate (gflops) for solve   =        2.418294        2.472308
     effective I/O rate (GB/sec) for solve   =        9.009562        9.210797

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        557056.        4. MB        555113.        4. MB
                95-   1       1671168.       13. MB       1647928.       13. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2203041.       17. MB


  Solver Memory allocated on core    0       =     1010.150 MB
  Solver Memory allocated on core    1       =     1277.795 MB
  Total Solver Memory allocated by all cores =     2287.946 MB





  Performance statistics for DSP solver: icalls =     40

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20700396
     no. of nonzeroes in the factor l        =       106129700
     ratio of nonzeroes in factor (min/max)  =          0.9483
     number of super nodes                   =            9122
     maximum order of a front matrix         =            4051
     maximum size of a front matrix          =         8207326
     maximum size of a front trapezoid       =         5395980
     no. of floating point ops for factor    =      1.3763D+11
     no. of floating point ops for solve     =      4.0549D+08
     ratio of flops for factor (min/max)     =          0.9611
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.390625        0.390543
     time (cpu & wall) for ordering          =        1.099731        1.099731
     time (cpu & wall) for other matrix prep =        0.369019        0.397128
     time (cpu & wall) for value input       =        0.296875        0.294805
     time (cpu & wall) for matrix distrib.   =        1.015625        1.036037
     time (cpu & wall) for numeric factor    =        4.578125        4.632486
     computational rate (gflops) for factor  =       30.062663       29.709887
     time (cpu & wall) for numeric solve     =        0.140625        0.137056
     computational rate (gflops) for solve   =        2.883488        2.958579
     effective I/O rate (GB/sec) for solve   =       10.742681       11.022442

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1048576.        8. MB       1048397.        8. MB
                95-   1       1179648.        9. MB       1153041.        9. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2201438.       17. MB


  Solver Memory allocated on core    0       =     1154.763 MB
  Solver Memory allocated on core    1       =     1072.118 MB
  Total Solver Memory allocated by all cores =     2226.881 MB





  Performance statistics for DSP solver: icalls =     41

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20708496
     no. of nonzeroes in the factor l        =       106250627
     ratio of nonzeroes in factor (min/max)  =          0.6064
     number of super nodes                   =            9113
     maximum order of a front matrix         =            4539
     maximum size of a front matrix          =        10303530
     maximum size of a front trapezoid       =         7224609
     no. of floating point ops for factor    =      1.4500D+11
     no. of floating point ops for solve     =      4.0553D+08
     ratio of flops for factor (min/max)     =          0.9577
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.343750        0.333113
     time (cpu & wall) for ordering          =        0.827698        0.827698
     time (cpu & wall) for other matrix prep =        0.297302        0.296696
     time (cpu & wall) for value input       =        0.250000        0.241753
     time (cpu & wall) for matrix distrib.   =        0.953125        0.971296
     time (cpu & wall) for numeric factor    =        4.765625        4.819363
     computational rate (gflops) for factor  =       30.426205       30.086942
     time (cpu & wall) for numeric solve     =        0.140625        0.147459
     computational rate (gflops) for solve   =        2.883804        2.750159
     effective I/O rate (GB/sec) for solve   =       10.743859       10.245955

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        557056.        4. MB        549574.        4. MB
                95-   1       1671168.       13. MB       1651936.       13. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2201510.       17. MB


  Solver Memory allocated on core    0       =      980.755 MB
  Solver Memory allocated on core    1       =     1270.600 MB
  Total Solver Memory allocated by all cores =     2251.356 MB





  Performance statistics for DSP solver: icalls =     42

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20558124
     no. of nonzeroes in the factor l        =       106932015
     ratio of nonzeroes in factor (min/max)  =          0.8207
     number of super nodes                   =            9096
     maximum order of a front matrix         =            3646
     maximum size of a front matrix          =         6648481
     maximum size of a front trapezoid       =         4913973
     no. of floating point ops for factor    =      1.3943D+11
     no. of floating point ops for solve     =      4.0874D+08
     ratio of flops for factor (min/max)     =          0.9145
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.281250        0.313261
     time (cpu & wall) for ordering          =        0.978638        0.978638
     time (cpu & wall) for other matrix prep =        0.271362        0.298956
     time (cpu & wall) for value input       =        0.218750        0.236614
     time (cpu & wall) for matrix distrib.   =        0.906250        0.907974
     time (cpu & wall) for numeric factor    =        4.484375        4.529909
     computational rate (gflops) for factor  =       31.091664       30.779138
     time (cpu & wall) for numeric solve     =        0.125000        0.138821
     computational rate (gflops) for solve   =        3.269909        2.944350
     effective I/O rate (GB/sec) for solve   =       12.182326       10.969428

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1310720.       10. MB       1292279.       10. MB
                95-   1        917504.        7. MB        905342.        7. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2197621.       17. MB


  Solver Memory allocated on core    0       =     1258.797 MB
  Solver Memory allocated on core    1       =      977.107 MB
  Total Solver Memory allocated by all cores =     2235.904 MB





  Performance statistics for DSP solver: icalls =     43

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20561932
     no. of nonzeroes in the factor l        =       108653621
     ratio of nonzeroes in factor (min/max)  =          0.7459
     number of super nodes                   =            9067
     maximum order of a front matrix         =            4315
     maximum size of a front matrix          =         9311770
     maximum size of a front trapezoid       =         6143865
     no. of floating point ops for factor    =      1.5283D+11
     no. of floating point ops for solve     =      4.1545D+08
     ratio of flops for factor (min/max)     =          0.9338
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.296875        0.294356
     time (cpu & wall) for ordering          =        0.880920        0.880920
     time (cpu & wall) for other matrix prep =        0.275330        0.292794
     time (cpu & wall) for value input       =        0.234375        0.220408
     time (cpu & wall) for matrix distrib.   =        0.953125        0.973852
     time (cpu & wall) for numeric factor    =        5.312500        5.333234
     computational rate (gflops) for factor  =       28.768789       28.656946
     time (cpu & wall) for numeric solve     =        0.140625        0.143717
     computational rate (gflops) for solve   =        2.954293        2.890739
     effective I/O rate (GB/sec) for solve   =       11.006474       10.769696

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        786432.        6. MB        779804.        6. MB
                95-   1       1441792.       11. MB       1416569.       11. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2196373.       17. MB


  Solver Memory allocated on core    0       =     1056.811 MB
  Solver Memory allocated on core    1       =     1196.777 MB
  Total Solver Memory allocated by all cores =     2253.588 MB





  Performance statistics for DSP solver: icalls =     44

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20574974
     no. of nonzeroes in the factor l        =       107041419
     ratio of nonzeroes in factor (min/max)  =          0.9524
     number of super nodes                   =            9050
     maximum order of a front matrix         =            3971
     maximum size of a front matrix          =         7886406
     maximum size of a front trapezoid       =         5852709
     no. of floating point ops for factor    =      1.4773D+11
     no. of floating point ops for solve     =      4.0912D+08
     ratio of flops for factor (min/max)     =          0.9827
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.343750        0.351201
     time (cpu & wall) for ordering          =        0.884949        0.884949
     time (cpu & wall) for other matrix prep =        0.286926        0.293924
     time (cpu & wall) for value input       =        0.203125        0.227814
     time (cpu & wall) for matrix distrib.   =        1.031250        1.199066
     time (cpu & wall) for numeric factor    =        5.062500        5.168983
     computational rate (gflops) for factor  =       29.181159       28.580018
     time (cpu & wall) for numeric solve     =        0.125000        0.144984
     computational rate (gflops) for solve   =        3.272963        2.821824
     effective I/O rate (GB/sec) for solve   =       12.193705       10.512947

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1048576.        8. MB       1040337.        8. MB
                95-   1       1179648.        9. MB       1153087.        9. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2193424.       17. MB


  Solver Memory allocated on core    0       =     1160.459 MB
  Solver Memory allocated on core    1       =     1110.171 MB
  Total Solver Memory allocated by all cores =     2270.630 MB





  Performance statistics for DSP solver: icalls =     45

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20476968
     no. of nonzeroes in the factor l        =       108774710
     ratio of nonzeroes in factor (min/max)  =          0.7292
     number of super nodes                   =            9097
     maximum order of a front matrix         =            4177
     maximum size of a front matrix          =         8725753
     maximum size of a front trapezoid       =         5124735
     no. of floating point ops for factor    =      1.5084D+11
     no. of floating point ops for solve     =      4.1610D+08
     ratio of flops for factor (min/max)     =          0.9277
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.328125        0.315588
     time (cpu & wall) for ordering          =        0.984558        0.984558
     time (cpu & wall) for other matrix prep =        0.296692        0.304372
     time (cpu & wall) for value input       =        0.250000        0.252543
     time (cpu & wall) for matrix distrib.   =        1.187500        1.503551
     time (cpu & wall) for numeric factor    =        6.171875        6.485296
     computational rate (gflops) for factor  =       24.439377       23.258272
     time (cpu & wall) for numeric solve     =        0.156250        0.162132
     computational rate (gflops) for solve   =        2.663016        2.566396
     effective I/O rate (GB/sec) for solve   =        9.921294        9.561330

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        819200.        6. MB        787149.        6. MB
                95-   1       1441792.       11. MB       1409555.       11. MB

                -------     ----------     --------     ----------     --------
                Totals:       2260992.       17. MB       2196704.       17. MB


  Solver Memory allocated on core    0       =     1049.563 MB
  Solver Memory allocated on core    1       =     1237.849 MB
  Total Solver Memory allocated by all cores =     2287.412 MB





  Performance statistics for DSP solver: icalls =     46

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20446292
     no. of nonzeroes in the factor l        =       104577698
     ratio of nonzeroes in factor (min/max)  =          0.7945
     number of super nodes                   =            9069
     maximum order of a front matrix         =            4198
     maximum size of a front matrix          =         8813701
     maximum size of a front trapezoid       =         5236836
     no. of floating point ops for factor    =      1.3439D+11
     no. of floating point ops for solve     =      3.9943D+08
     ratio of flops for factor (min/max)     =          0.9416
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.328125        0.333142
     time (cpu & wall) for ordering          =        1.062439        1.062439
     time (cpu & wall) for other matrix prep =        0.312561        0.336417
     time (cpu & wall) for value input       =        0.281250        0.284159
     time (cpu & wall) for matrix distrib.   =        1.218750        1.380611
     time (cpu & wall) for numeric factor    =        5.406250        5.713278
     computational rate (gflops) for factor  =       24.857877       23.522031
     time (cpu & wall) for numeric solve     =        0.156250        0.149265
     computational rate (gflops) for solve   =        2.556331        2.675954
     effective I/O rate (GB/sec) for solve   =        9.523831        9.969498

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        851968.        6. MB        835149.        6. MB
                95-   1       1376256.       10. MB       1355584.       10. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2190733.       17. MB


  Solver Memory allocated on core    0       =     1073.079 MB
  Solver Memory allocated on core    1       =     1139.166 MB
  Total Solver Memory allocated by all cores =     2212.245 MB





  Performance statistics for DSP solver: icalls =     47

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20500712
     no. of nonzeroes in the factor l        =       102421186
     ratio of nonzeroes in factor (min/max)  =          0.6728
     number of super nodes                   =            9074
     maximum order of a front matrix         =            4129
     maximum size of a front matrix          =         8526385
     maximum size of a front trapezoid       =         5071455
     no. of floating point ops for factor    =      1.2552D+11
     no. of floating point ops for solve     =      3.9074D+08
     ratio of flops for factor (min/max)     =          0.9942
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.328125        0.324193
     time (cpu & wall) for ordering          =        0.913025        0.913025
     time (cpu & wall) for other matrix prep =        0.321350        0.334070
     time (cpu & wall) for value input       =        0.328125        0.327053
     time (cpu & wall) for matrix distrib.   =        1.046875        1.206363
     time (cpu & wall) for numeric factor    =        4.656250        4.802375
     computational rate (gflops) for factor  =       26.957789       26.137529
     time (cpu & wall) for numeric solve     =        0.140625        0.153447
     computational rate (gflops) for solve   =        2.778590        2.546409
     effective I/O rate (GB/sec) for solve   =       10.351876        9.486864

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        786432.        6. MB        757341.        6. MB
                95-   1       1441792.       11. MB       1435634.       11. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2192975.       17. MB


  Solver Memory allocated on core    0       =      979.367 MB
  Solver Memory allocated on core    1       =     1203.561 MB
  Total Solver Memory allocated by all cores =     2182.928 MB





  Performance statistics for DSP solver: icalls =     48

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20498972
     no. of nonzeroes in the factor l        =       104907377
     ratio of nonzeroes in factor (min/max)  =          0.9583
     number of super nodes                   =            9057
     maximum order of a front matrix         =            4216
     maximum size of a front matrix          =         8889436
     maximum size of a front trapezoid       =         5214066
     no. of floating point ops for factor    =      1.3395D+11
     no. of floating point ops for solve     =      4.0067D+08
     ratio of flops for factor (min/max)     =          0.9219
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.312500        0.314585
     time (cpu & wall) for ordering          =        0.896301        0.896301
     time (cpu & wall) for other matrix prep =        0.306824        0.301742
     time (cpu & wall) for value input       =        0.265625        0.256632
     time (cpu & wall) for matrix distrib.   =        0.875000        0.869676
     time (cpu & wall) for numeric factor    =        4.656250        4.652514
     computational rate (gflops) for factor  =       28.768129       28.791231
     time (cpu & wall) for numeric solve     =        0.171875        0.172907
     computational rate (gflops) for solve   =        2.331182        2.317263
     effective I/O rate (GB/sec) for solve   =        8.685020        8.633164

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1146880.        9. MB       1144953.        9. MB
                95-   1       1048576.        8. MB       1047502.        8. MB

                -------     ----------     --------     ----------     --------
                Totals:       2195456.       17. MB       2192455.       17. MB


  Solver Memory allocated on core    0       =     1164.497 MB
  Solver Memory allocated on core    1       =     1047.648 MB
  Total Solver Memory allocated by all cores =     2212.145 MB





  Performance statistics for DSP solver: icalls =     49

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20455355
     no. of nonzeroes in the factor l        =       104230435
     ratio of nonzeroes in factor (min/max)  =          0.7775
     number of super nodes                   =            9076
     maximum order of a front matrix         =            4195
     maximum size of a front matrix          =         8801110
     maximum size of a front trapezoid       =         5317158
     no. of floating point ops for factor    =      1.3293D+11
     no. of floating point ops for solve     =      3.9809D+08
     ratio of flops for factor (min/max)     =          0.9537
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.390625        0.394631
     time (cpu & wall) for ordering          =        0.928162        0.928162
     time (cpu & wall) for other matrix prep =        0.353088        0.375579
     time (cpu & wall) for value input       =        0.218750        0.230834
     time (cpu & wall) for matrix distrib.   =        1.031250        1.035647
     time (cpu & wall) for numeric factor    =        6.109375        6.308962
     computational rate (gflops) for factor  =       21.757837       21.069519
     time (cpu & wall) for numeric solve     =        0.156250        0.159356
     computational rate (gflops) for solve   =        2.547751        2.498099
     effective I/O rate (GB/sec) for solve   =        9.491865        9.306882

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        917504.        7. MB        900299.        7. MB
                95-   1       1310720.       10. MB       1291959.       10. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2192258.       17. MB


  Solver Memory allocated on core    0       =     1075.300 MB
  Solver Memory allocated on core    1       =     1125.639 MB
  Total Solver Memory allocated by all cores =     2200.939 MB





  Performance statistics for DSP solver: icalls =     50

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =          232766
     no. of nonzeroes in lower triangle of a =        20554355
     no. of nonzeroes in the factor l        =       105153209
     ratio of nonzeroes in factor (min/max)  =          0.8953
     number of super nodes                   =            9095
     maximum order of a front matrix         =            4318
     maximum size of a front matrix          =         9324721
     maximum size of a front trapezoid       =         5536125
     no. of floating point ops for factor    =      1.3654D+11
     no. of floating point ops for solve     =      4.0168D+08
     ratio of flops for factor (min/max)     =          0.9055
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             168
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.328125        0.343798
     time (cpu & wall) for ordering          =        0.995117        0.995117
     time (cpu & wall) for other matrix prep =        0.270508        0.313844
     time (cpu & wall) for value input       =        0.343750        0.335379
     time (cpu & wall) for matrix distrib.   =        1.078125        1.111898
     time (cpu & wall) for numeric factor    =        5.656250        5.776840
     computational rate (gflops) for factor  =       24.138978       23.635084
     time (cpu & wall) for numeric solve     =        0.156250        0.196629
     computational rate (gflops) for solve   =        2.570720        2.042810
     effective I/O rate (GB/sec) for solve   =        9.577439        7.610666

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0       1277952.       10. MB       1254256.       10. MB
                95-   1        950272.        7. MB        940955.        7. MB

                -------     ----------     --------     ----------     --------
                Totals:       2228224.       17. MB       2195211.       17. MB


  Solver Memory allocated on core    0       =     1248.158 MB
  Solver Memory allocated on core    1       =      977.161 MB
  Total Solver Memory allocated by all cores =     2225.319 MB

